/*******************************************************************************
 *
 *    Copyright 2020 Adobe. All rights reserved.
 *    This file is licensed to you under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License. You may obtain a copy
 *    of the License at http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software distributed under
 *    the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR REPRESENTATIONS
 *    OF ANY KIND, either express or implied. See the License for the specific language
 *    governing permissions and limitations under the License.
 *
 ******************************************************************************/

package com.adobe.cq.commerce.magento.graphql;

import java.util.Map;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.shopify.graphql.support.AbstractResponse;
import com.shopify.graphql.support.ID;
import com.shopify.graphql.support.SchemaViolationError;

/**
 * Contains information used to generate PayPal iframe for transaction. Applies to Payflow Link and
 * Payments Advanced payment methods.
 */
public class PayflowLinkToken extends AbstractResponse<PayflowLinkToken> {
    public PayflowLinkToken() {
    }

    public PayflowLinkToken(JsonObject fields) throws SchemaViolationError {
        for (Map.Entry<String, JsonElement> field : fields.entrySet()) {
            String key = field.getKey();
            String fieldName = getFieldName(key);
            switch (fieldName) {
                case "mode": {
                    PayflowLinkMode optional1 = null;
                    if (!field.getValue().isJsonNull()) {
                        optional1 = PayflowLinkMode.fromGraphQl(jsonAsString(field.getValue(), key));
                    }

                    responseData.put(key, optional1);

                    break;
                }

                case "paypal_url": {
                    String optional1 = null;
                    if (!field.getValue().isJsonNull()) {
                        optional1 = jsonAsString(field.getValue(), key);
                    }

                    responseData.put(key, optional1);

                    break;
                }

                case "secure_token": {
                    String optional1 = null;
                    if (!field.getValue().isJsonNull()) {
                        optional1 = jsonAsString(field.getValue(), key);
                    }

                    responseData.put(key, optional1);

                    break;
                }

                case "secure_token_id": {
                    String optional1 = null;
                    if (!field.getValue().isJsonNull()) {
                        optional1 = jsonAsString(field.getValue(), key);
                    }

                    responseData.put(key, optional1);

                    break;
                }

                case "__typename": {
                    responseData.put(key, jsonAsString(field.getValue(), key));
                    break;
                }

                default: {
                    readCustomField(fieldName, field.getValue());
                }
            }
        }
    }

    public String getGraphQlTypeName() {
        return "PayflowLinkToken";
    }

    /**
     * Mode for Payflow transaction
     */
    public PayflowLinkMode getMode() {
        return (PayflowLinkMode) get("mode");
    }

    public PayflowLinkToken setMode(PayflowLinkMode arg) {
        optimisticData.put(getKey("mode"), arg);
        return this;
    }

    /**
     * PayPal URL used for requesting Payflow form
     */
    public String getPaypalUrl() {
        return (String) get("paypal_url");
    }

    public PayflowLinkToken setPaypalUrl(String arg) {
        optimisticData.put(getKey("paypal_url"), arg);
        return this;
    }

    /**
     * Secure token generated by PayPal
     */
    public String getSecureToken() {
        return (String) get("secure_token");
    }

    public PayflowLinkToken setSecureToken(String arg) {
        optimisticData.put(getKey("secure_token"), arg);
        return this;
    }

    /**
     * Secure token ID generated by PayPal
     */
    public String getSecureTokenId() {
        return (String) get("secure_token_id");
    }

    public PayflowLinkToken setSecureTokenId(String arg) {
        optimisticData.put(getKey("secure_token_id"), arg);
        return this;
    }

    public boolean unwrapsToObject(String key) {
        switch (getFieldName(key)) {
            case "mode": return false;

            case "paypal_url": return false;

            case "secure_token": return false;

            case "secure_token_id": return false;

            default: return false;
        }
    }
}
